language: node_js
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # Allow vX.X.X tags
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      name: Verify compilation
      node_js: lts/*
      script: yarn compile
    - stage: test
      name: Lint code
      node_js: lts/*
      script: yarn lint
    - stage: test
      name: Run tests (Node.js Current)
      node_js: node
    - stage: test
      name: Run tests (Node.js LTS)
      node_js: lts/*
      script:
        # - yarn global add codecov
        - yarn test
        # - codecov
    - stage: deploy
      if: type = push AND tag IS present
      name: Deploy to npm
      node_js: lts/*
      script:
        - yarn compile
        - echo "Deploying to npm..."
      deploy:
        provider: npm
        skip_cleanup: true
        email: wes@sparksuite.com
        api_key:
          secure: "B/jeQyxOiyRH8+9IzheW0yA3iBFePR7ox6l5xQqYhQcTEh4puW4wdjXL1GHvZjnS3XF5Um1I6Jftwt71YeYl+oggxqPEPrTdQsh07ByDF1rfTzRgRCAcgOIm1skqKApKzP1/3ZoHVNT84TZlA4t959cTDNOHiun6uZmk/gXhGT1CnORaEvD6l2PCC3puDQGMcbZRFe0ERWOFfrG0F9mAt5m3NJZcnYcqCX+xijInnya0J1+RDgOJseyIzKB3qiRWtdgTN2vSJShTSFFO+UnUCDRBqb6zq+cQrKXhUhqvnKXfv3DwmCRZ85fnlv1VU0JSLoIWUgGmcYrOWIKQd9yU97p1LRvERgoKVYIdV6khaznryubg0jmBA0A4p6BXwH7lLu5aRFmHihRyZRinpS4J8LogXqSA43RwGUV0NsVRCqvdE26gzqdytG76feFHncqY9Sl4vTt6Ow9eitc0QE0dMrhzANeq5NGyoLTzgassZsCImzJMzSac6RofZ5Sab+NWxmqBbgzQvCLzIjW0uMIpLq3p3qZt/g1rmi2hKyU4PLqUG4BXIys5O17i3b/m0sljnyENJ/8DBrWe2Shhiis1xieZKOiEC1q/dT5Qmn9VWDlm19TFDYNtBNj/K8OTY4LBwmO9QupDXNcUWlwXybgW6ez14bphCfGIJ2N8N9N5qKQ="
        on:
          tags: true
